default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
  - repo: local
    hooks:
      # - id: eslint
      #   name: ESLint
      #   entry: pnpm run eslint:check
      #   language: system
      #   stages:
      #     - pre-commit
      - id: prettier
        name: Prettier
        entry: pnpm run prettier:check
        language: system
        stages:
          - pre-commit
      # - id: px
      #   name: px check
      #   entry: ./scripts/git-hooks/check.sh px
      #   language: script
      - id: rgba
        name: rgba check
        entry: ./scripts/git-hooks/check.sh rgba
        language: script
      - id: hex
        name: hex check
        entry: ./scripts/git-hooks/check.sh hex
        language: script
      - id: audit-check
        name: Vulnerability check
        entry: pnpm run audit
        language: system
        stages:
          - pre-push
      - id: license-check
        name: License compliance check
        entry: pnpm run license-compliance
        language: system
        stages:
          - pre-push
      - id: verify-committer-email
        name: Enforce committer email
        entry: ./scripts/git-hooks/verify-committer-email.sh
        language: script
        stages:
          - commit-msg
      - id: check-building
        name: Check for building
        entry: pnpm run build
        language: system
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.1
    hooks:
      - id: gitleaks
        stages:
          - pre-commit
